### ISSUE TITLE
Get ID Check Modal Working for WP Localhost

### ISSUE THREAD

**Issue by OpenDoorBrewCo** [OpenDoorBrewCo/odbc-wp#3]
The ID check modal is currently not displaying correctly on local host or staging WP versions of site. 

It should look like this:
![image](https://cloud.githubusercontent.com/assets/10080818/5428986/b1ee1c10-8397-11e4-8108-a45137b29dec.png)

But it currently looks like this: 
![image](https://cloud.githubusercontent.com/assets/10080818/5428988/c6cfc642-8397-11e4-85ff-72bc3c528ebd.png)

**Comment by michaelbadaracca** [comment]
Updated **Age Check** content page. The path on the cookie was being set to odbc.localhost/age-check instead of odbc.localhost (root). This means the cookie was not persisted in the right scope and the age check modal kept appearing.

updated 
`document.cookie = "OfDrinkingAge=" + OfDrinkingAge;`

to
`document.cookie = "OfDrinkingAge=" + OfDrinkingAge + "; path=/;";`

A useful resource: http://www.thesitewizard.com/javascripts/cookies.shtml
